import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Design System: Orbit Interactive 3D Navigation (Stitch 2343664840906902405)
        background: '#12131a',
        surface: '#12131a',
        'surface-dim': '#12131a',
        'surface-bright': '#383940',
        'surface-container-lowest': '#0c0e14',
        'surface-container-low': '#1a1b22',
        'surface-container': '#1e1f26',
        'surface-container-high': '#282a31',
        'surface-container-highest': '#33343c',
        'surface-variant': '#33343c',
        'on-surface': '#e2e1eb',
        'on-surface-variant': '#b9cacb',
        'inverse-surface': '#e2e1eb',
        'inverse-on-surface': '#2f3037',
        outline: '#849495',
        'outline-variant': '#3a494b',
        'surface-tint': '#00dbe7',
        primary: '#e1fdff',
        'on-primary': '#00363a',
        'primary-container': '#00f2ff',
        'on-primary-container': '#006a71',
        'inverse-primary': '#00696f',
        secondary: '#c8c6c5',
        'on-secondary': '#313030',
        'secondary-container': '#4a4949',
        'on-secondary-container': '#bab8b7',
        'secondary-fixed': '#e5e2e1',
        'secondary-fixed-dim': '#c8c6c5',
        'on-secondary-fixed': '#1c1b1b',
        'on-secondary-fixed-variant': '#474646',
        tertiary: '#faf6f6',
        'on-tertiary': '#313030',
        'tertiary-container': '#dddad9',
        'on-tertiary-container': '#615f5f',
        'tertiary-fixed': '#e5e2e1',
        'tertiary-fixed-dim': '#c9c6c5',
        'on-tertiary-fixed': '#1c1b1b',
        'on-tertiary-fixed-variant': '#474646',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#74f5ff',
        'primary-fixed-dim': '#00dbe7',
        'on-primary-fixed': '#002022',
        'on-primary-fixed-variant': '#004f54',
        // Keep accent for compatibility
        accent: '#7C3AED',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
        // Keep sm and md for compatibility
        sm: '0.25rem',
        md: '0.75rem',
      },
      spacing: {
        base: '8px',
        'grid-columns': '12',
        gutter: '24px',
        'container-max': '1440px',
        margin: '64px',
        // Keep section-gap for compatibility
        'section-gap': '160px',
      },
      fontFamily: {
        'h1': ['Space Grotesk'],
        'h2': ['Space Grotesk'],
        'h3': ['Space Grotesk'],
        'body-md': ['Inter'],
        'body-lg': ['Inter'],
        'label-caps': ['Space Grotesk'],
        // Keep existing for compatibility
        sans: ['Inter', 'system-ui', 'sans-serif'],
        'headline-lg': ['Space Grotesk'],
        'headline-md': ['Space Grotesk'],
        'body-sm': ['Inter'],
        'display-xl': ['Space Grotesk'],
      },
      fontSize: {
        'h1': ['64px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'h2': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'h3': ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.15em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
        // Keep existing for compatibility
        'headline-lg': ['64px', { lineHeight: '120%', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '130%', letterSpacing: '0.02em', fontWeight: '500' }],
        'display-xl': ['120px', { lineHeight: '110%', letterSpacing: '-0.04em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '160%', letterSpacing: '0.01em', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
export default config;
